//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 05:00:18 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sujetos.esios.ree.es/schemas/2014/04/01/PerfilConsumo-esios-MP/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package models.ree.perfiles;
