//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 05:01:51 PM CEST 
//


package models.ree.desgloses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the models.ree.desgloses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: models.ree.desgloses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PVPCDesgloseHorario }
     * 
     */
    public PVPCDesgloseHorario createPVPCDesgloseHorario() {
        return new PVPCDesgloseHorario();
    }

    /**
     * Create an instance of {@link IdentificacionMensajeType }
     * 
     */
    public IdentificacionMensajeType createIdentificacionMensajeType() {
        return new IdentificacionMensajeType();
    }

    /**
     * Create an instance of {@link VersionMensajeType }
     * 
     */
    public VersionMensajeType createVersionMensajeType() {
        return new VersionMensajeType();
    }

    /**
     * Create an instance of {@link TipoMensajeType }
     * 
     */
    public TipoMensajeType createTipoMensajeType() {
        return new TipoMensajeType();
    }

    /**
     * Create an instance of {@link TipoProcesoType }
     * 
     */
    public TipoProcesoType createTipoProcesoType() {
        return new TipoProcesoType();
    }

    /**
     * Create an instance of {@link TipoClasificacionType }
     * 
     */
    public TipoClasificacionType createTipoClasificacionType() {
        return new TipoClasificacionType();
    }

    /**
     * Create an instance of {@link IdentificacionRemitenteType }
     * 
     */
    public IdentificacionRemitenteType createIdentificacionRemitenteType() {
        return new IdentificacionRemitenteType();
    }

    /**
     * Create an instance of {@link FuncionRemitenteType }
     * 
     */
    public FuncionRemitenteType createFuncionRemitenteType() {
        return new FuncionRemitenteType();
    }

    /**
     * Create an instance of {@link IdentificacionDestinatarioType }
     * 
     */
    public IdentificacionDestinatarioType createIdentificacionDestinatarioType() {
        return new IdentificacionDestinatarioType();
    }

    /**
     * Create an instance of {@link FuncionDestinatarioType }
     * 
     */
    public FuncionDestinatarioType createFuncionDestinatarioType() {
        return new FuncionDestinatarioType();
    }

    /**
     * Create an instance of {@link FechaHoraMensajeType }
     * 
     */
    public FechaHoraMensajeType createFechaHoraMensajeType() {
        return new FechaHoraMensajeType();
    }

    /**
     * Create an instance of {@link HorizonteType }
     * 
     */
    public HorizonteType createHorizonteType() {
        return new HorizonteType();
    }

    /**
     * Create an instance of {@link SeriesTemporalesType }
     * 
     */
    public SeriesTemporalesType createSeriesTemporalesType() {
        return new SeriesTemporalesType();
    }

    /**
     * Create an instance of {@link IdentificacionSeriesTemporalesType }
     * 
     */
    public IdentificacionSeriesTemporalesType createIdentificacionSeriesTemporalesType() {
        return new IdentificacionSeriesTemporalesType();
    }

    /**
     * Create an instance of {@link MediaPeriodoType }
     * 
     */
    public MediaPeriodoType createMediaPeriodoType() {
        return new MediaPeriodoType();
    }

    /**
     * Create an instance of {@link CtdType }
     * 
     */
    public CtdType createCtdType() {
        return new CtdType();
    }

    /**
     * Create an instance of {@link PeriodoType }
     * 
     */
    public PeriodoType createPeriodoType() {
        return new PeriodoType();
    }

    /**
     * Create an instance of {@link UnidadPrecioType }
     * 
     */
    public UnidadPrecioType createUnidadPrecioType() {
        return new UnidadPrecioType();
    }

    /**
     * Create an instance of {@link ResolucionType }
     * 
     */
    public ResolucionType createResolucionType() {
        return new ResolucionType();
    }

    /**
     * Create an instance of {@link IntervaloType }
     * 
     */
    public IntervaloType createIntervaloType() {
        return new IntervaloType();
    }

    /**
     * Create an instance of {@link IntervaloTiempoType }
     * 
     */
    public IntervaloTiempoType createIntervaloTiempoType() {
        return new IntervaloTiempoType();
    }

    /**
     * Create an instance of {@link TerminoCosteHorarioType }
     * 
     */
    public TerminoCosteHorarioType createTerminoCosteHorarioType() {
        return new TerminoCosteHorarioType();
    }

    /**
     * Create an instance of {@link PosType }
     * 
     */
    public PosType createPosType() {
        return new PosType();
    }

    /**
     * Create an instance of {@link TipoPrecioType }
     * 
     */
    public TipoPrecioType createTipoPrecioType() {
        return new TipoPrecioType();
    }

}
