//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 05:01:51 PM CEST 
//


package models.ree.desgloses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IntervaloTiempo" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}IntervaloTiempoType"/>
 *         &lt;element name="Resolucion" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}ResolucionType"/>
 *         &lt;element name="MediaPeriodo" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}MediaPeriodoType"/>
 *         &lt;element name="Intervalo" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}IntervaloType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodoType", propOrder = {
    "intervaloTiempo",
    "resolucion",
    "mediaPeriodo",
    "intervalo"
})
public class PeriodoType {

    @XmlElement(name = "IntervaloTiempo", required = true)
    protected IntervaloTiempoType intervaloTiempo;
    @XmlElement(name = "Resolucion", required = true)
    protected ResolucionType resolucion;
    @XmlElement(name = "MediaPeriodo", required = true)
    protected MediaPeriodoType mediaPeriodo;
    @XmlElement(name = "Intervalo")
    protected List<IntervaloType> intervalo;

    /**
     * Gets the value of the intervaloTiempo property.
     * 
     * @return
     *     possible object is
     *     {@link IntervaloTiempoType }
     *     
     */
    public IntervaloTiempoType getIntervaloTiempo() {
        return intervaloTiempo;
    }

    /**
     * Sets the value of the intervaloTiempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervaloTiempoType }
     *     
     */
    public void setIntervaloTiempo(IntervaloTiempoType value) {
        this.intervaloTiempo = value;
    }

    /**
     * Gets the value of the resolucion property.
     * 
     * @return
     *     possible object is
     *     {@link ResolucionType }
     *     
     */
    public ResolucionType getResolucion() {
        return resolucion;
    }

    /**
     * Sets the value of the resolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResolucionType }
     *     
     */
    public void setResolucion(ResolucionType value) {
        this.resolucion = value;
    }

    /**
     * Gets the value of the mediaPeriodo property.
     * 
     * @return
     *     possible object is
     *     {@link MediaPeriodoType }
     *     
     */
    public MediaPeriodoType getMediaPeriodo() {
        return mediaPeriodo;
    }

    /**
     * Sets the value of the mediaPeriodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaPeriodoType }
     *     
     */
    public void setMediaPeriodo(MediaPeriodoType value) {
        this.mediaPeriodo = value;
    }

    /**
     * Gets the value of the intervalo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intervalo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntervalo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IntervaloType }
     * 
     * 
     */
    public List<IntervaloType> getIntervalo() {
        if (intervalo == null) {
            intervalo = new ArrayList<IntervaloType>();
        }
        return this.intervalo;
    }

}
