//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 05:01:51 PM CEST 
//


package models.ree.desgloses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SeriesTemporalesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SeriesTemporalesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacionSeriesTemporales" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}IdentificacionSeriesTemporalesType"/>
 *         &lt;element name="TerminoCosteHorario" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}TerminoCosteHorarioType"/>
 *         &lt;element name="TipoPrecio" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}TipoPrecioType" minOccurs="0"/>
 *         &lt;element name="UnidadPrecio" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}UnidadPrecioType"/>
 *         &lt;element name="Periodo" type="{http://sujetos.esios.ree.es/schemas/2014/04/01/PVPCDesgloseHorario-esios-MP/}PeriodoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeriesTemporalesType", propOrder = {
    "identificacionSeriesTemporales",
    "terminoCosteHorario",
    "tipoPrecio",
    "unidadPrecio",
    "periodo"
})
public class SeriesTemporalesType {

    @XmlElement(name = "IdentificacionSeriesTemporales", required = true)
    protected IdentificacionSeriesTemporalesType identificacionSeriesTemporales;
    @XmlElement(name = "TerminoCosteHorario", required = true)
    protected TerminoCosteHorarioType terminoCosteHorario;
    @XmlElement(name = "TipoPrecio")
    protected TipoPrecioType tipoPrecio;
    @XmlElement(name = "UnidadPrecio", required = true)
    protected UnidadPrecioType unidadPrecio;
    @XmlElement(name = "Periodo", required = true)
    protected PeriodoType periodo;

    /**
     * Gets the value of the identificacionSeriesTemporales property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificacionSeriesTemporalesType }
     *     
     */
    public IdentificacionSeriesTemporalesType getIdentificacionSeriesTemporales() {
        return identificacionSeriesTemporales;
    }

    /**
     * Sets the value of the identificacionSeriesTemporales property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificacionSeriesTemporalesType }
     *     
     */
    public void setIdentificacionSeriesTemporales(IdentificacionSeriesTemporalesType value) {
        this.identificacionSeriesTemporales = value;
    }

    /**
     * Gets the value of the terminoCosteHorario property.
     * 
     * @return
     *     possible object is
     *     {@link TerminoCosteHorarioType }
     *     
     */
    public TerminoCosteHorarioType getTerminoCosteHorario() {
        return terminoCosteHorario;
    }

    /**
     * Sets the value of the terminoCosteHorario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminoCosteHorarioType }
     *     
     */
    public void setTerminoCosteHorario(TerminoCosteHorarioType value) {
        this.terminoCosteHorario = value;
    }

    /**
     * Gets the value of the tipoPrecio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPrecioType }
     *     
     */
    public TipoPrecioType getTipoPrecio() {
        return tipoPrecio;
    }

    /**
     * Sets the value of the tipoPrecio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPrecioType }
     *     
     */
    public void setTipoPrecio(TipoPrecioType value) {
        this.tipoPrecio = value;
    }

    /**
     * Gets the value of the unidadPrecio property.
     * 
     * @return
     *     possible object is
     *     {@link UnidadPrecioType }
     *     
     */
    public UnidadPrecioType getUnidadPrecio() {
        return unidadPrecio;
    }

    /**
     * Sets the value of the unidadPrecio property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnidadPrecioType }
     *     
     */
    public void setUnidadPrecio(UnidadPrecioType value) {
        this.unidadPrecio = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodoType }
     *     
     */
    public PeriodoType getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodoType }
     *     
     */
    public void setPeriodo(PeriodoType value) {
        this.periodo = value;
    }

}
